### ISSUE TITLE
05-legacy-host.md 单词拼写错误

### ISSUE THREAD

**Issue by tylerzou0760** [deepflowio/docs#712]
文档:
https://www.deepflow.io/docs/zh/ce-install/legacy-host/#%E6%9B%B4%E6%96%B0-deepflow-server-%E9%85%8D%E7%BD%AE
源码:
https://github.com/deepflowio/docs/blob/main/docs/zh/02-ce-install/05-legacy-host.md?plain=1

描述：
原代码中trident-type-for-unkonw-vtap: 3 # required 的unkonw 拼写错误，正确为unknow

错误---
修改 `values-custom.yaml` 自定义配置文件：

```yaml
configmap:
  server.yaml:
    controller:
      genesis:
        local_ip_ranges:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
          - 169.254.0.0/15
          - 224.0.0.0-240.255.255.255
          - 100.42.32.0/24 # FIXME
      trisolaris:
        trident-type-for-unkonw-vtap: 3 # required
```
